name: Update data files version

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Update data files version in pastry fish server
      uses: fjogeleit/http-request-action@master
      with:
        url: ${{ secrets.PASTRY_FISH_SERVER_HOST }}/records/dataFilesVersion/${{ github.sha }}
        method: "PUT"
        bearerToken: ${{ secrets.PASTRY_FISH_SERVER_ACCESS_TOKEN }}
        
